# -*- mode: makefile; -*-

BOOST_CPPFLAGS += -DBOOST_SPIRIT_THREADSAFE

BOOST_LIBS =                                    \
    $(BOOST_FILESYSTEM_LIBS)                    \
    $(BOOST_IOSTREAMS_LIBS)                     \
    $(BOOST_PROGRAM_OPTIONS_LIBS)               \
    $(BOOST_REGEX_LIBS)                         \
    $(BOOST_SYSTEM_LIBS)                        \
    $(BOOST_THREAD_LIBS)

AM_CPPFLAGS = -I. -I$(top_srcdir)/include $(BOOST_CPPFLAGS)

AM_LDFLAGS  =                                   \
    $(BOOST_FILESYSTEM_LDFLAGS)                 \
    $(BOOST_IOSTREAMS_LDFLAGS)                  \
    $(BOOST_PROGRAM_OPTIONS_LDFLAGS)            \
    $(BOOST_REGEX_LDFLAGS)                      \
    $(BOOST_SYSTEM_LDFLAGS)                     \
    $(BOOST_THREAD_LDFLAGS)

LIBS = $(BOOST_LIBS)
