# -*- mode: makefile; -*-

BOOST_CPPFLAGS += -DBOOST_SPIRIT_THREADSAFE

AM_CPPFLAGS = -I. -I$(top_srcdir)/include $(BOOST_CPPFLAGS)

BOOST_LIBS =                                    \
    $(BOOST_FILESYSTEM_LIBS)                    \
    $(BOOST_IOSTREAMS_LIBS)                     \
    $(BOOST_PROGRAM_OPTIONS_LIBS)               \
    $(BOOST_SYSTEM_LIBS)                        \
    $(BOOST_THREAD_LIBS)                        \
    $(BOOST_TIMER_LIBS)

LIBS = $(BOOST_LIBS)
